### ISSUE TITLE
ACTION_BLOCKED

### ISSUE THREAD

**Issue by ATLCap** [KiNoYo/rotation-builder#8]
Hello, I keep getting this error (captured with BugSack) no matter what toon I'm using:

```
1x [ADDON_ACTION_BLOCKED] AddOn 'RotationBuilder' tried to call the protected function 'CompactRaidFrame3:SetAttribute()'.
```

Could another addon be interfering or is an updated Blizzard api causing it?

Love the addon, thanks!

**Comment by vdubus** [comment]
Sorry, but no method `CompactRaidFrame3:SetAttribute` exist in our code…
Which mean that Rotation Builder is wrongly accused in this case (seems to be a common problem).

Best solution here to find out the problem, is to disable every other addon but Rotation Builder, and then reproduce the problem enabling addon by addon one at the time…

Do you have any information on how to reproduce the problem? For what I see, it seems that the raid panel is part of the problem. So check addon which touch this part in priority.

> Love the addon, thanks!

We are happy to know that you love it.  😄

**Comment by vdubus** [comment]
No response, so we will assume there was no problem.
