### ISSUE TITLE
Unable to load texture file

### ISSUE THREAD

**Issue by pejub** [KiNoYo/rotation-builder#9]
Hi

I get multiple texture loading errors for three functions:
ROB_SetNextActionTint, ROB_AO_ActionIcon_OnTextChanged and ROB_SetCurrentActionTint

Checking the XML the file= references no file.

Is there a setting I can change to get rid of the errors?

**Comment by vdubus** [comment]
Hello.

It's a problem what we are currently trying to figure out. But no luck until now.
This don't seems to impact Rotation Builder or WoW in any way (work fine after), so it isn't in high priority.

Unless… Did a popup show up to tell you about this error?

In this case, I would suggest to install [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber) and [BugSack](https://www.curseforge.com/wow/addons/bugsack).
You will still have a warning (but no popup), and will be able to easily copy/paste the error to us (or any other addon).

**Comment by vdubus** [comment]
The bug was fixed.
Will be release soon.
